# Generated by Django 5.2.2 on 2025-06-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=1000)),
                ('email_address', models.CharField(max_length=1000)),
                ('hours_of_operations', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icons', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=500)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HourOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_name', models.CharField(max_length=100)),
                ('days_works', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='More_Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=50)),
                ('step_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('step_icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('facebook_link', models.CharField(max_length=10000)),
                ('twitter_link', models.CharField(max_length=10000)),
                ('linkedin_link', models.CharField(max_length=10000)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50)),
                ('first_paragraph', models.CharField(max_length=1000)),
                ('second_paragraph', models.CharField(max_length=1000)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
