# Generated by Django 5.2.2 on 2025-06-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='More_Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
