# Generated by Django 5.2.2 on 2025-06-16 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_more_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_culture',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
