# Generated by Django 5.2.2 on 2025-06-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fulirugalleymodel_viragalleymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('write_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
