# Generated by Django 5.2.2 on 2025-06-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_stepmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50)),
                ('first_paragraph', models.CharField(max_length=1000)),
                ('second_paragraph', models.CharField(max_length=1000)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
