# Generated by Django 5.2.2 on 2025-06-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_testimonialmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('facebook_link', models.CharField(max_length=10000)),
                ('twitter_link', models.CharField(max_length=10000)),
                ('linkedin_link', models.CharField(max_length=10000)),
                ('image_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
