# Generated by Django 5.2.2 on 2025-06-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_icons_teammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000000)),
            ],
        ),
    ]
