# Generated by Django 5.2.2 on 2025-06-28 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_galleries_galleryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleries',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
