# Generated by Django 5.2.2 on 2025-06-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_suggestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=1000)),
                ('email_address', models.CharField(max_length=1000)),
                ('hours_of_operations', models.CharField(max_length=1000)),
            ],
        ),
    ]
