# Generated by Django 5.2.2 on 2025-06-28 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_galleries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
