# Generated by Django 5.2.2 on 2025-06-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_galleryimages_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtSocietyModel',
        ),
        migrations.DeleteModel(
            name='FuliruGalleyModel',
        ),
        migrations.DeleteModel(
            name='LanguageCustomsModel',
        ),
        migrations.DeleteModel(
            name='ViraGalleyModel',
        ),
    ]
