# Generated by Django 5.2.2 on 2025-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_addressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HourOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_name', models.CharField(max_length=100)),
                ('days_works', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
    ]
