# Generated by Django 5.2.2 on 2025-06-16 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_emailmodel_hourofoperation_locationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icons',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
