# Generated by Django 5.2.2 on 2025-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_artsocietymodel_delete_fulirugalleymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(max_length=10000000),
        ),
    ]
