# Generated by Django 5.2.2 on 2025-06-30 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_feature_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeName', models.CharField(max_length=100)),
                ('yearOfTaken', models.DateField()),
                ('yearOfDeath', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='myapp.feature')),
            ],
        ),
    ]
