# Generated by Django 5.2.2 on 2025-06-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_featuredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredetails',
            name='yearOfDeath',
            field=models.DateField(blank=True, null=True),
        ),
    ]
