# Generated by Django 5.2.2 on 2025-06-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_featuredetails_yearofdeath'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredetails',
            name='encore_vivant',
            field=models.BooleanField(default=False),
        ),
    ]
