# Generated by Django 5.2.2 on 2025-07-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_featuredetails_encore_vivant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='iskingdom',
            field=models.BooleanField(default=True),
        ),
    ]
